//! SeaORM Entity. Generated by sea-orm-codegen 0.12.15
#![allow(unused_imports)]

pub use super::app_settings::Entity as AppSettings;
pub use super::asset_diary_entries::Entity as AssetDiaryEntries;
pub use super::asset_notes::Entity as AssetNotes;
pub use super::asset_snippets::Entity as AssetSnippets;
pub use super::asset_vault_entries::Entity as AssetVaultEntries;
pub use super::links::Entity as Links;
pub use super::project_activity_logs::Entity as ProjectActivityLogs;
pub use super::project_links::Entity as ProjectLinks;
pub use super::project_tags::Entity as ProjectTags;
pub use super::projects::Entity as Projects;
pub use super::spaces::Entity as Spaces;
pub use super::tags::Entity as Tags;
pub use super::task_activity_logs::Entity as TaskActivityLogs;
pub use super::task_links::Entity as TaskLinks;
pub use super::task_tags::Entity as TaskTags;
pub use super::tasks::Entity as Tasks;
