//! SeaORM Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::Priority;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub space_id: String,
    pub parent_id: Option<String>,
    pub path: String,
    pub title: String,
    pub note: Option<String>,
    pub priority: Priority,
    pub todo_task_count: i64,
    pub done_task_count: i64,
    pub last_task_updated_at: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
    pub archived_at: Option<i64>,
    pub deleted_at: Option<i64>,
    pub create_by: String,
    pub rank: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::spaces::Entity",
        from = "Column::SpaceId",
        to = "super::spaces::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Spaces,
    #[sea_orm(has_many = "super::tasks::Entity")]
    Tasks,
}

impl Related<super::spaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spaces.def()
    }
}

impl Related<super::tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tasks.def()
    }
}

#[allow(dead_code)]
pub struct SelfRefLink;
impl Linked for SelfRefLink {
    type FromEntity = Entity;
    type ToEntity = Entity;
    fn link(&self) -> Vec<RelationDef> {
        vec![Relation::SelfRef.def()]
    }
}

impl ActiveModelBehavior for ActiveModel {}
